import './globals.css';
import { Inter } from 'next/font/google';
import Navbar from './components/navbar'; // Import the Client Component

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'AI Image Generator',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar /> {/* Use the Client Component for navigation */}
        {children}
      </body>
    </html>
  );
}